[EASI-3082] CRA -> Vite migration (#2163)
* Add Vite and required packages

* Create vite.config.ts

* Move and update index.html

- Move index.html to root folder
- Remove %PUBLIC_URL% references
- Add Vite entry point

* Update tsconfig.json

* Create vite-env.d.ts

* Remove react-scripts

- Remove react-scripts
- Delete react-app-env.d.ts

* Update scripts in package.json

* Update env variables

* Change build output folder

* Remove craco

* Configure vite.config.ts for docker

* Updated caniuse-lite

Not necessary for vite migration, but removed warning message to update.

* Upgraded react-csv

Previous version was incompatible with Vite because Link component was .js file instead of .jsx

* Set scss load paths

* Hide uswds console notifications

* Upgrade storybook

* Upgrade Apollo

* Fix build script

* Fix Okta bug

* Fix uswds theme paths

* Enable css source maps

* Add autoprefixer

* Add autoprefixer to vite.config.ts

* Add vitest

* Snapshots

* Remove Jest canvas mock

* BusinessCaseReview test error

Error: Uncaught [TypeError: Cannot read properties of null (reading 'offsetWidth')]

* Upgrade Vite

Multiple installed versions of vite was causing type error

* Add vitest globals to tsconfig

* Add vi global to .eslintrc

* Replace jest global with vi

* Set global timezone

- Renamed jest-global-setup.js to global-setup.js
- Set timezone to UTC in global-setup.js
- Added globalSetup file to vite.config.ts

* Mock getTrbRequestDocumentsQuery

- Added mocked query to src/data/mock/trbRequest.ts
- Fixed missing mock query error in Consult.test.tsx

* Snapshots

* Added Vitest UI package

* Added vitest:ui

Opens unit tests in Vitest UI

* Removed jest-launchdarkly-references

* Fix createObjectURL JSDOM error

- Fixes error from react-csv: "TypeError: The "obj" argument must be an instance of Blob. Received an instance of Blob"
- JSDOM does not support window.URL.createObjectURL, so needed to mock in setupTests.ts

* Clay changes for vitest canvas mock, WIP, non functional

* Fix navigationBar test

* Fix setupTests typeError

* Fix Header unit test errors

- Fixed typo
- Wrapped component in Provider
- Updated to async function

* Enable threads

- Disabling threads causes tests to fail
- See https://github.com/vitest-dev/vitest/issues/1430

* Fix flaky TRB Consult test

Test randomly threw error that no more mocked responses were available for getTRBRequestAttendeesQuery. Duplicating the query in the mocks array fixed this.

* Skip Tabs test

* Snapshots

* Update yarn.lock

* Update snapshot

* Remove unit tests that render Okta signin widget

* Remove vitest-canvas-mock

* Add role attribute to csv download link

byRole queries in unit tests were not recognizing csv download links as links because the href prop isn't set. Explicitly setting "role=link" solved this.

* Fix "cannot find offset width of null" error

* Fix unit test classlist argument error

* Remove vitest UI

* Fix references to REACT_APP_ env vars that have not yet been converted to use VITE_

* Enable test coverage when running yarn test:coverage with v8. See https://vitest.dev/guide/coverage.html for info

* Fix cypress plugins env variables bug

Changed import.meta.env to process.env

* Add cypress-vite

- Removed cypress/webpack-preprocessor
- Added cypress-vite

* Cypress-vite config updates

* Empty commit

* Debug file:preprocessor

* Upgrade Cypress

* Comment out tests that import app code

* Comment out missed suite with imports

* Re-introduce webpack for Cypress

* Uncomment tests

* Cleanup

- Removed commented out debug code
- Uncommented e2e test code

* Enable cypress video

* Set long timeout on Okta login

* Try clicking multiple times

* Try clicking multiple times

* Upgrade okta-signin-widget from 6 to 7

* Undo multi click in Cypress

* import css from okta widget using exported path. Add commonjsOptions to transform require to import in imported modules

* Remove extra setting of VITE_OKTA_REDIRECT_URI

* Remove references to craco, add ADR

* Remove unused packages. Add comments, remove TODO comments.

---------

Co-authored-by: ClayBenson94 <clay.benson@oddball.io>